// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="sw_led_control_sw_led_control,hls_ip_2023_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvu11p-flga2577-1-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=0.000000,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=0,HLS_SYN_LUT=0,HLS_VERSION=2023_2}" *)

module sw_led_control (
        sw0,
        sw1,
        sw2,
        sw3,
        sw4,
        led0,
        led1,
        led2,
        led3,
        led4
);


input  [0:0] sw0;
input  [0:0] sw1;
input  [0:0] sw2;
input  [0:0] sw3;
input  [0:0] sw4;
input  [0:0] led0;
input  [0:0] led1;
input  [0:0] led2;
input  [0:0] led3;
input  [0:0] led4;

endmodule //sw_led_control
