// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="ComCir_ComCir,hls_ip_2023_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvu11p-flga2577-1-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=0.148000,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=0,HLS_SYN_LUT=6,HLS_VERSION=2023_2}" *)

module ComCir (
        a,
        b,
        c,
        d
);


input  [0:0] a;
input  [0:0] b;
input  [0:0] c;
output  [0:0] d;

wire   [0:0] and_ln11_fu_57_p2;
wire   [0:0] xor_ln11_fu_63_p2;

assign and_ln11_fu_57_p2 = (b & a);

assign xor_ln11_fu_63_p2 = (c ^ 1'd1);

assign d = (xor_ln11_fu_63_p2 | and_ln11_fu_57_p2);

endmodule //ComCir
