-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity sw_led_control is
port (
    sw0 : IN STD_LOGIC_VECTOR (0 downto 0);
    sw1 : IN STD_LOGIC_VECTOR (0 downto 0);
    sw2 : IN STD_LOGIC_VECTOR (0 downto 0);
    sw3 : IN STD_LOGIC_VECTOR (0 downto 0);
    sw4 : IN STD_LOGIC_VECTOR (0 downto 0);
    led0 : IN STD_LOGIC_VECTOR (0 downto 0);
    led1 : IN STD_LOGIC_VECTOR (0 downto 0);
    led2 : IN STD_LOGIC_VECTOR (0 downto 0);
    led3 : IN STD_LOGIC_VECTOR (0 downto 0);
    led4 : IN STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of sw_led_control is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "sw_led_control_sw_led_control,hls_ip_2023_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvu11p-flga2577-1-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=0.000000,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=0,HLS_SYN_LUT=0,HLS_VERSION=2023_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';



begin



end behav;
